- name: terraform apply
  hosts: localhost
  gather_facts: yes
  become_user: sudo
  tasks:
  - name: plan
    terraform:
     project_path: '/root/terraform/login'
     plan_file: 'provider'
     force_init: yes
     lock: true
     state: planned

  - name: apply
    terraform:
     project_path: '/root/terraform/login'
     lock: true
     state: present
