- name: terraform destroy
  hosts: localhost
  gather_facts: yes
  become_user: sudo
  tasks:
  - name: plan
    terraform:
     project_path: '/root/terraform/login'
     plan_file: 'provider'
     lock: true
     state: planned

  - name: destroy
    terraform:
     project_path: '/root/terraform/login'
     lock: true
     state: absent
