- name: check for packages
  hosts: all
  tasks:
   - name: yum_command 
     yum: list=installed
     register: yum_packages
   - name: Print package search result
     debug:
     var: yum_packages
